# INFO
site_name: 韩永琰的个人网站 # 左上角标题
site_url: https://hanyongyan.github.io
site_author: 韩永琰
site_description: 韩永琰的个人网站

# [UI]
## [top]
theme:
  name: material
  palette: 
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features:
    - navigation.tabs # 使用Tab来进行分类
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.indexes # Tab会有一个index.md 而不是在打开Tab时打开第一篇文章
    - navigation.expand # 打开Tab时左侧目录全部展开
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
  language: zh # 一些提示性的文字会变成中文
  icon:
    repo: fontawesome/brands/github
edit_uri: edit/main/docs # 编辑按钮跳转的链接
## [top-right corner]
repo_url: https://github.com/hanyongyan/hanyongyan.github.io # 右上角点击跳转的链接
repo_name: hanyongyan.github.io # 右上角的名字
## [bottom-left corner]
copyright: Copyright &copy; 2022 韩永琰 # 左下角的版权声明
## [bottom-right corner]
extra:
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/358218864
      name: Bilibili | 愿你决定 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/hanyongyan
      name: GitHub | hanyongyan

# [Navigtion]
nav:
  - 学习笔记: 
    - StudyNodes/index.md
    - Linux:
      - Linux入门: StudyNodes/Linux/Linux.md
      - Vim: StudyNodes/Linux/Vim.md
    - MySql:
      - Mysql: StudyNodes/MySql/MySQL笔记.md
    - js: 
      - Ajax: StudyNodes/JS/Ajax.md
      - jQuery: StudyNodes/JS/jQuery.md
      - javaScript: StudyNodes/JS/JS.md
      - nodejs: StudyNodes/JS/Node.js.md
    - java: 
      - JavaWeb: StudyNodes/Java/JavaWeb.md
      - Maven: StudyNodes/Java/Maven.md
      - MyBatis: StudyNodes/Java/MyBatis笔记.md
      - MyBatisPlus: StudyNodes/Java/MyBatisPlus.md
      - SSM: StudyNodes/Java/SSM.md
      - 瑞吉外卖笔记: StudyNodes/Java/瑞吉外卖笔记.md
      - Nacos: StudyNodes/Java/Nacos安装指南.md
    - Git:
      - git: StudyNodes/Git/Git.md
      - 1.1Git简易指南: StudyNodes/Git/2.1-Git简易指南(上).md
      - 1.2创建代码仓库: StudyNodes/Git/2.2-创建代码仓库.md
      - 1.3保存更改: StudyNodes/Git/2.3-保存你的更改.md
      - 1.4查看仓库状态: StudyNodes/Git/2.4-查看仓库状态.md
      - 1.5检查以前的提交: StudyNodes/Git/2.5-检查以前的提交.md
      - 1.6回滚错误的修改: StudyNodes/Git/2.6-回滚错误的修改.md
      - 1.7重写项目历史: StudyNodes/Git/2.7-重写项目历史.md
      - 2.1保持代码同步: StudyNodes/Git/3.2-保持代码同步.md
      - 2.2创建PullRequest: StudyNodes/Git/3.3-创建PullRequest.md
      - 2.3使用分支: StudyNodes/Git/3.4-使用分支.md
      - 2.4常见工作流比较: StudyNodes/Git/常见工作流比较.md
      - 3Git图解: StudyNodes/Git/4-Git图解.md
      - 4.1代码合并Merge还是Rebase: StudyNodes/Git/5.1-代码合并Merge还是Rebase.md
      - 4.2回滚命令: StudyNodes/Git/5.2-回滚命令Reset、Checkout、Revert辨析.md
      - 4.3Git_log高级用法: StudyNodes/Git/5.3-Git_log高级用法.md
      - 4.4Git钩子: StudyNodes/Git/5.4-Git钩子.md
      - 4.5Git提交引用: StudyNodes/Git/5.5-Git提交引用.md

# [Extensions]
plugins:
  - search: # 现在还不支持中文搜索 支持之后可以设置语言
    # insider已经支持中文的分词搜索了 https://squidfunk.github.io/mkdocs-material/blog/2022/chinese-search-support/
      lang:
        - en
        - ja
  - tags # 给单篇文章添加标签 https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/?h=tags
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      # linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols